---
language: python
python:
    - 2.7
services:
    - docker
install:
    - docker build -t keepalived-centos7-rpm-builder .
script:
    - docker run -ti --rm -v $PWD/data:/data -v $PWD/assets/config:/config keepalived-centos7-rpm-builder start.sh
